export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const TWITTER_CLIENT_ID = process.env.NEXT_PUBLIC_TWITTER_CLIENT_ID;
export const TWITTER_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_TWITTER_CLIENT_SECRET;
